# Generated by Django 6.1.1 on 2026-09-26 05:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('creators', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Briefing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('youtube_url', models.URLField(blank=True, max_length=500)),
                ('duration', models.CharField(default='10:00', max_length=20)),
                ('thumbnail_url', models.URLField(blank=True, max_length=500)),
                ('summary', models.TextField(help_text='Short teaser/recap summary')),
                ('full_summary', models.TextField(help_text='Full detailed breakdown')),
                ('key_takeaways', models.JSONField(default=list, help_text='List of key points')),
                ('audio_url', models.URLField(blank=True, max_length=500)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='audio_briefings/')),
                ('timeframe', models.CharField(choices=[('daily', 'Daily Briefing'), ('weekly', 'Weekly Digest'), ('both', 'Both Daily & Weekly')], default='daily', max_length=20)),
                ('category', models.CharField(default='General', max_length=100)),
                ('listens_count', models.PositiveIntegerField(default=0)),
                ('saves_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='briefings', to='creators.creator')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
