# Generated by Django 6.1.1 on 2026-09-26 05:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('briefings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.IntegerField(default=5, help_text='Rating 1 to 5')),
                ('useful_feedback', models.CharField(blank=True, help_text='e.g. Very clear, Confusing or unclear', max_length=200)),
                ('thoughts', models.TextField(blank=True, help_text='User comments or thoughts')),
                ('request_improved', models.BooleanField(default=False)),
                ('request_option', models.CharField(default='Feedback submitted', max_length=150)),
                ('is_platform_review', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('summary_tag', models.CharField(default='Great summary', max_length=100)),
                ('better_version_tag', models.CharField(default='Generate a better version', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('briefing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to='briefings.briefing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
