# Generated by Django 6.1.1 on 2026-09-26 05:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address', models.CharField(default='Dhaka, Bangladesh', max_length=255)),
                ('email', models.EmailField(default='info@curio.com', max_length=254)),
                ('mobile', models.CharField(default='+8801688148194', max_length=50)),
                ('facebook', models.CharField(blank=True, default='CurioAI', max_length=150)),
                ('x_profile', models.CharField(blank=True, default='@CurioAI', max_length=150)),
                ('instagram', models.CharField(blank=True, default='@curio.ai', max_length=150)),
                ('terms_of_use', models.TextField(blank=True)),
                ('privacy_policy', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
