# Generated by Django 6.1.1 on 2026-09-26 05:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('handle', models.CharField(max_length=100, unique=True)),
                ('channel_url', models.URLField(blank=True, max_length=500)),
                ('avatar_url', models.URLField(blank=True, max_length=500)),
                ('initials', models.CharField(blank=True, max_length=10)),
                ('avatar_gradient', models.CharField(default='bg-gradient-to-tr from-cyan-500 to-blue-600', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('video_count', models.IntegerField(default=0)),
                ('subscriber_count', models.CharField(default='0 subscribers', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CreatorFollow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='creators.creator')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_creators', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'creator')},
            },
        ),
    ]
